# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghx < Formula
  desc "A keyboard-driven TUI for GitHub — PRs, Issues, Actions, and Notifications in one place"
  homepage "https://github.com/onnga-wasabi/ghx"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onnga-wasabi/ghx/releases/download/v0.3.4/ghx_darwin_amd64.tar.gz"
      sha256 "abce9cacbcc93ba20c314ea33b69c3a8f5065c6f8d5060caee062c72a316d7d2"

      define_method(:install) do
        bin.install "ghx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onnga-wasabi/ghx/releases/download/v0.3.4/ghx_darwin_arm64.tar.gz"
      sha256 "32b9be95ef4e1fabd6d1692256ccbb4a2e7cdd1053eeba1459250c552901cd05"

      define_method(:install) do
        bin.install "ghx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onnga-wasabi/ghx/releases/download/v0.3.4/ghx_linux_amd64.tar.gz"
      sha256 "bae22a14cd668773b1e53941bf74c332bd9418dbdc674b5d0c81d43fec204925"
      define_method(:install) do
        bin.install "ghx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onnga-wasabi/ghx/releases/download/v0.3.4/ghx_linux_arm64.tar.gz"
      sha256 "af5045490a0d431c97f90977b17990e46a38633c772ecd9e2a03581fc6b17de4"
      define_method(:install) do
        bin.install "ghx"
      end
    end
  end
end
